### ISSUE TITLE
Error on installation

### ISSUE THREAD

**Issue by aaryanporwal** [KhushrajRathod/hcload#8]
I'm a new user to deno and this stuff, and was trying to install this application on windows 11.
This is the error I'm getting:
```
> deno install --unstable -A https://deno.land/x/hcload/hcload.ts
Check https://deno.land/x/hcload/hcload.ts
error: TS2339 [ERROR]: Property 'getIterator' does not exist on type 'ReadableStream<R>'.
  return res.readable.getIterator();
                      ~~~~~~~~~~~
    at https://deno.land/std@0.73.0/async/pool.ts:45:23
```
![image](https://user-images.githubusercontent.com/54525904/152415943-09d9245e-e87c-49f8-9b49-c02078a97319.png)

```
> deno --version
deno 1.18.1 (release, x86_64-pc-windows-msvc)
v8 9.8.177.6
typescript 4.5.2

```

**Comment by khrj** [comment]
Looks like a previously unstable API broke with a newer version of Deno.
I've fixed it in [v1.3.2](https://deno.land/x/hcload@1.3.2) - All of the APIs should now be stable, so `--unstable` is no longer needed.

**Comment by aaryanporwal** [comment]
It's still broken
```
$ deno install -A https://deno.land/x/hcload/hcload.ts
Check https://deno.land/x/hcload/hcload.ts
error: TS2339 [ERROR]: Property 'getIterator' does not exist on type 'ReadableStream<R>'.
  return res.readable.getIterator();
                      ~~~~~~~~~~~
    at https://deno.land/std@0.73.0/async/pool.ts:45:23

TS2339 [ERROR]: Property 'utime' does not exist on type 'typeof Deno'. 'Deno.utime' is an unstable API. Did you forget to run with the '--unstable' flag?
    await Deno.utime(dest, statInfo.atime, statInfo.mtime);
               ~~~~~
    at https://deno.land/std@0.74.0/fs/copy.ts:92:16

TS2339 [ERROR]: Property 'utimeSync' does not exist on type 'typeof Deno'. 'Deno.utimeSync' is an unstable API. Did you forget to run with the '--unstable' flag?
    Deno.utimeSync(dest, statInfo.atime, statInfo.mtime);
         ~~~~~~~~~
    at https://deno.land/std@0.74.0/fs/copy.ts:103:10

TS2339 [ERROR]: Property 'utime' does not exist on type 'typeof Deno'. 'Deno.utime' is an unstable API. Did you forget to run with the '--unstable' flag?
    await Deno.utime(dest, statInfo.atime, statInfo.mtime);
               ~~~~~
    at https://deno.land/std@0.74.0/fs/copy.ts:127:16

TS2339 [ERROR]: Property 'utimeSync' does not exist on type 'typeof Deno'. 'Deno.utimeSync' is an unstable API. Did you forget to run with the '--unstable' flag?
    Deno.utimeSync(dest, statInfo.atime, statInfo.mtime);
         ~~~~~~~~~
    at https://deno.land/std@0.74.0/fs/copy.ts:152:10

TS2339 [ERROR]: Property 'utime' does not exist on type 'typeof Deno'. 'Deno.utime' is an unstable API. Did you forget to run with the '--unstable' flag?
    await Deno.utime(dest, srcStatInfo.atime, srcStatInfo.mtime);
               ~~~~~
    at https://deno.land/std@0.74.0/fs/copy.ts:172:16

TS2339 [ERROR]: Property 'utimeSync' does not exist on type 'typeof Deno'. 'Deno.utimeSync' is an unstable API. Did you forget to run with the '--unstable' flag?
    Deno.utimeSync(dest, srcStatInfo.atime, srcStatInfo.mtime);
         ~~~~~~~~~
    at https://deno.land/std@0.74.0/fs/copy.ts:200:10

Found 7 errors.
```

**Comment by khrj** [comment]
Could you share the version of deno you have installed?
```
deno --version
```

**Comment by aaryanporwal** [comment]
```
$ deno --version
deno 1.18.1 (release, x86_64-pc-windows-msvc)
v8 9.8.177.6
typescript 4.5.2
```

**Comment by khrj** [comment]
You'll need a newer version of Deno, try [v1.20.4](https://github.com/denoland/deno/releases/tag/v1.20.4). Some of these APIs only hit stable with 1.20

**Comment by aaryanporwal** [comment]
It's not working on the latest version for me, is it working for you?

**Comment by khrj** [comment]
I'm on Deno v1.19.1, and it works for me:
![image](https://user-images.githubusercontent.com/44947946/162183840-4850fd3e-fb15-41cc-9245-7e971aab1290.png)
